<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WKMCA7382527" failures="1" tests="2" name="ValidateTitle" time="20.551" errors="0" timestamp="2021-02-27T08:16:04 IST">
  <testcase classname="pratice.ValidateTitle" name="validateAppTitle" time="0.041"/>
  <testcase classname="pratice.ValidateTitle" name="validateHeader" time="0.032">
    <failure type="java.lang.AssertionError" message="expected [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING 123] but found [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING]">
      <![CDATA[java.lang.AssertionError: expected [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING 123] but found [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING]
at pratice.ValidateTitle.validateHeader(ValidateTitle.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateHeader -->
</testsuite> <!-- ValidateTitle -->
